# Generated by Django 4.0.2 on 2022-02-10 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siteName', models.CharField(max_length=200)),
                ('siteAddress', models.TextField(blank=True, null=True)),
                ('siteCity', models.CharField(max_length=200)),
                ('siteOwner', models.CharField(max_length=200)),
                ('siteVendor', models.CharField(max_length=200)),
                ('siteProvider', models.CharField(max_length=200)),
                ('siteFN', models.CharField(max_length=200)),
                ('siteFiles', models.FileField(blank=True, null=True, upload_to='')),
                ('siteDescription', models.TextField(blank=True, null=True)),
                ('is4T6S', models.BinaryField(default=False)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
