# Generated by Django 4.0.2 on 2022-02-13 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EastSites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='acceptanceDate',
            field=models.DateField(null=True, verbose_name='Acceptance'),
        ),
        migrations.AddField(
            model_name='site',
            name='changedParts',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='freqIs2600F1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='site',
            name='freqIs2600F2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='site',
            name='freqis800',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='site',
            name='sitKPIrepo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='site',
            name='siteCellId',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='siteFiberLength',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='siteHistory',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='siteIP',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='siteLatitude',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='siteLongitude',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='siteMaintenanceDates',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='siteOwnerNumber',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='siteSFPType',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='siteTower',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='siteType',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='is4T6S',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='site',
            name='pub_date',
            field=models.DateTimeField(null=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='site',
            name='siteCity',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='siteFN',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='siteName',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='siteOwner',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='siteProvider',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='siteVendor',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
